### ISSUE TITLE
log pulls in std: how do I disable the std feature on the log crate?

### ISSUE THREAD

**Issue by gauteh** [rust-embedded-community/embedded-sdmmc-rs#44]
Optionally add `default-features = false` to log in you Cargo.toml.

Is this even possible?

```
embedded-sdmmc-rs on  develop [$] via 🦀 v1.59.0-nightly
❯ cargo build --target=thumbv7em-none-eabihf
   Compiling log v0.4.14
error[E0463]: can't find crate for `std`
  |
  = note: the `thumbv7em-none-eabihf` target may not support the standard library
  = note: `std` is required by `log` because it does not declare `#![no_std]`
  = help: consider building the standard library from source with `cargo build -Zbuild-std`

For more information about this error, try `rustc --explain E0463`.
error: could not compile `log` due to previous error
```

**Comment by gauteh** [comment]
Seems like something happened when going from log 0.3 to 0.4, it works with log 0.3.6.

**Comment by eldruin** [comment]
@gauteh  Can this be solved by using `resolver = "2"` in the `Cargo.toml`?

**Comment by gauteh** [comment]
Not sure, but with #45 this is no longer an issue for me.

**Comment by Laura7089** [comment]
I'm having this issue as well.

> Related: https://github.com/rafalh/rust-fatfs/issues/39

Could it be that the `env_logger` dev dep is pulling in a `log` with `std` enabled?

**Comment by Laura7089** [comment]
Might it be worth providing no-op implementation(s) of any `log` macros used for if the `log` and `defmt-log` features are both disabled?

**Comment by gauteh** [comment]
Normally that is what `log` does if no logger is set up. It seems that `std` is pulled in because of dev/test dependencies (features). Might be solved by the suggestion of using `resolver = 2`. It is a bit more cumbersome to disable the statements completely.

I tried looking for a noop log crate, but this is already the standard log crate with no loggers.
